package Interfaz;

import javax.swing.*;
import Logica.*;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class DialogPrincipal extends javax.swing.JDialog {

    private Cliente cliente;

    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public DialogPrincipal(Cliente cliente, javax.swing.JFrame parent, boolean modal) {
        super(parent, modal);
        this.cliente = cliente;
        initComponents();
        Sistema.centrarContainer(this);
        tablaRes.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
    //El método valueChange se debe sobreescribir obligatoriamente. 
    //Se ejecuta automáticamente cada vez que se hace una nueva selección. 
            /**
             * abre una ventana restaurante con el restaurante seleccionado
             */
    @Override 
    public void valueChanged(ListSelectionEvent e) { 
            int indiceFila = tablaRes.getSelectedRow();  
            String nom =(String) tablaRes.getValueAt(indiceFila, 0);
            for (Restaurante res: Sistema.buscarCercanos(cliente)){
                if (res.getNombre().equals(nom) ){                
                    new JRestaurante(DialogPrincipal.this, true, res).setVisible(true);
                    break;
                }
                
            }
    }});
    }
    /**
     * crea una matriz necesaria para reflejar los datos de los restaurante en una tabla
     * @param restaurantes
     * @return String[][]  
     */
    public String [] [] obtenerResumen(ArrayList<Restaurante> restaurantes){
          String [][] resumen = new String[restaurantes.size()][3];
          int i =0;
          for (Restaurante res : restaurantes){
              resumen [i][0] = res.getNombre();
              resumen [i][1] = res.getEspecialidad().name();
              if (res.getNumCalificaciones()!=0){
                  double nota10= Math.round(res.calcularCalificacion()*10);
              resumen [i][2] = String.valueOf(nota10/10);
              }
              else resumen[i][2] = "Sin calificar";
              i++;
          }
         return resumen;   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        comboBoxOrdenar = new javax.swing.JComboBox<>();
        jLabel = new javax.swing.JLabel();
        TextFieldBusqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonLupa = new javax.swing.JButton();
        jButtonEncontrado = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaRes = new javax.swing.JTable();
        botonEdDatos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        logo1 = new Interfaz.Logo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        setIconImage(null);
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollBar1.setBackground(new java.awt.Color(255, 204, 102));
        jScrollPane1.setViewportView(jScrollBar1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        comboBoxOrdenar.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        String[] opciones;
        if (cliente instanceof ClienteEmpresa){
            opciones = new String[]{"por cercanía","solo Catering", "relevancia", "tiempo de envio", "especialidad"};
        }else opciones = new String[]{"por cercanía","relevancia", "tiempo de envío", "especialidad"};
        comboBoxOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(opciones));
        comboBoxOrdenar.setSelectedItem("por cercanía");
        comboBoxOrdenar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        comboBoxOrdenar.setFocusable(false);
        comboBoxOrdenar.setInheritsPopupMenu(true);
        comboBoxOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxOrdenarActionPerformed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        jLabel.setText("ordenar resultados: ");

        TextFieldBusqueda.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        TextFieldBusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        jLabel1.setText("busca un restaurante (nombre o cif)");

        try{
            File input = new File("src/main/java/Imagenes/lupa.png");
            ImageIcon imagen = new ImageIcon (ImageIO.read(input));
            jButtonLupa.setIcon(imagen);
            jButtonLupa.setBorder(null);
        }catch(IOException ioe){
            System.out.println("Error I/O : no carga la lupa");
        }
        catch (NullPointerException npe){
            System.out.println("Error NullPointer en boton lupa");
        }
        jButtonLupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLupaActionPerformed(evt);
            }
        });

        jButtonEncontrado.setVisible(false);
        jButtonEncontrado.setFont(new java.awt.Font("Bodoni MT", 2, 14)); // NOI18N
        jButtonEncontrado.setText("¡ pincha aquí !");

        tablaRes.setModel(new javax.swing.table.DefaultTableModel(
            obtenerResumen(Sistema.buscarCercanos(cliente)),
            new String [] {
                "Restaurante", "Especialidad", "Calificación"
            }
        ));
        tablaRes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaRes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tablaRes);

        try{
            File input = new File("src/main/java/Imagenes/lapizEditar.jpg");
            ImageIcon imagen = new ImageIcon (ImageIO.read(input));
            botonEdDatos.setIcon(new javax.swing.ImageIcon(imagen.getImage()));
        }
        catch (IOException ioe){
            System.out.println("error en boton lapiz editar");
        }
        botonEdDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEdDatosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        jLabel2.setText("editar perfil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonEdDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2))
                                    .addComponent(comboBoxOrdenar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonLupa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonEncontrado)
                                    .addComponent(jLabel1))))
                        .addGap(0, 157, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(botonEdDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(comboBoxOrdenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLupa, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        getParent().setVisible(true);
        
    }//GEN-LAST:event_formWindowClosed

    /**
     * si el texto introducido coindice con algun nombre o cif de los restaurantes dados de alta,
     * pone en visible un botón que al pinchar te lleva a su ventana Restaurante
     * @param evt 
     */
    
    private void jButtonLupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLupaActionPerformed
        String busqueda = TextFieldBusqueda.getText();
        boolean existe = false;
        Restaurante res = null;
        if (Sistema.getRestaurantes().containsKey(busqueda)){//si lo busca por cif
            res = Sistema.getRestaurantes().get(busqueda);
            existe = true;
                    }
        else{//si lo busca por nombre
            for (Restaurante rest: Sistema.restaurantesArrayList()){
                if (rest.getNombre().equals(busqueda)){
                    existe = true;
                    res= rest;
                    break;
                }
            }
        }
        if (!existe){
            JOptionPane.showMessageDialog(this, "No existe ese restaurante", "Not Found", JOptionPane.ERROR_MESSAGE);
        }
        else {
            try{
            final JDialog  parent = this;
            final Restaurante rest = res;
            jButtonEncontrado.setVisible(true);
            jButtonEncontrado.addActionListener((ActionEvent e) -> {
                new JRestaurante(parent, true,rest).setVisible(true);
                parent.setVisible(false);
            });
            }catch(NullPointerException npe){
                System.out.println(npe.getMessage());
            }
        }
        
            
                
           
            
        
    }//GEN-LAST:event_jButtonLupaActionPerformed
/**
 * ordena  filtra los restaurantes del combobox segun el criteri seleccionado
 * @param evt 
 */
    private void comboBoxOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxOrdenarActionPerformed
        String eleccion =(String) comboBoxOrdenar.getSelectedItem();
        ArrayList<Restaurante> restaurantes= new ArrayList<>();
        switch (eleccion){
            case ("por cercanía")->{
                restaurantes = Sistema.buscarCercanos(cliente);
            }
            case ("relevancia")-> {
                restaurantes = Sistema.ordenarRelevancia(Sistema.buscarCercanos(cliente));
            }case("tiempo de envío")->{
                restaurantes = Sistema.ordenarTiempoEnvio(Sistema.buscarCercanos(cliente));
            }case("solo Catering")->{
                restaurantes = Sistema.filtrarCatering(Sistema.buscarCercanos(cliente));
            }case ("especialidad")->{
                int espec = JOptionPane.showOptionDialog(this,
                        "selecciona especialidad",
                        "ESPECIALIDAD",
                        JOptionPane.DEFAULT_OPTION, 
                        JOptionPane.PLAIN_MESSAGE, 
                        null,
                        Restaurante.especialidades.values(),
                        Restaurante.especialidades.CHINO);
                try{
                restaurantes = Sistema.filtrarEspecialidad(Sistema.buscarCercanos(cliente), Restaurante.especialidades.values()[espec]);}
                catch(ArrayIndexOutOfBoundsException e){
                    restaurantes = Sistema.buscarCercanos(cliente);
                }
            }
        }
            tablaRes.setModel(new javax.swing.table.DefaultTableModel(
    obtenerResumen(restaurantes),
         new String [] {
           "Restaurante", "Especialidad", "Calificación"
    }
));        
    }//GEN-LAST:event_comboBoxOrdenarActionPerformed

    private void botonEdDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEdDatosActionPerformed
        new JEditarDatos(this, true, cliente);
        this.setVisible(false);
    }//GEN-LAST:event_botonEdDatosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldBusqueda;
    private javax.swing.JButton botonEdDatos;
    private javax.swing.JComboBox<String> comboBoxOrdenar;
    private javax.swing.JButton jButtonEncontrado;
    private javax.swing.JButton jButtonLupa;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private Interfaz.Logo logo1;
    private javax.swing.JTable tablaRes;
    // End of variables declaration//GEN-END:variables
}
