package Interfaz;

import Logica.Cliente;
import Logica.Pedido;
import Logica.Restaurante;
import Logica.Sistema;
import java.text.ParseException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

public class JAdmin extends javax.swing.JDialog {

    /**
     * Creates new form JAdmin
     */
    public JAdmin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Sistema.centrarContainer(this);
        panelRes.setVisible(false);
        panelClis.setVisible(false);
        panelPedidos.setVisible(false);
        String a ="";
        for (Restaurante res:Sistema.restaurantesArrayList()){
            a += res.getNombre() +", ";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelRes = new javax.swing.JPanel();
        cbRestaurantes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDarDeBaja = new javax.swing.JRadioButton();
        jModRes = new javax.swing.JRadioButton();
        jDarDeAlta = new javax.swing.JRadioButton();
        jInfoCliente = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jVerInfoRes = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        botonVentas = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        panelPedidos = new javax.swing.JPanel();
        cbPedidos = new javax.swing.JComboBox<>();
        try{
            MaskFormatter dateFormatter = new MaskFormatter("####/##/## ##:##:##");
            dateFormatter.setPlaceholderCharacter('_');
            fechaElegida = new javax.swing.JFormattedTextField(dateFormatter);
        }catch(ParseException pe){
            System.out.println(pe.getMessage());
        }
        buttonFiltrarFecha = new javax.swing.JButton();
        logo1 = new Interfaz.Logo();
        panelClis = new javax.swing.JPanel();
        cbClientes = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel1.setText("Dar de alta a un restaurante");

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel2.setText("Modificar datos de un restaurante");

        panelRes.setBackground(new java.awt.Color(255, 255, 255));

        cbRestaurantes.setModel(new javax.swing.DefaultComboBoxModel<>(Restaurante.obtenerNombres(Sistema.restaurantesArrayList())));
        cbRestaurantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRestaurantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelResLayout = new javax.swing.GroupLayout(panelRes);
        panelRes.setLayout(panelResLayout);
        panelResLayout.setHorizontalGroup(
            panelResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResLayout.createSequentialGroup()
                .addComponent(cbRestaurantes, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        panelResLayout.setVerticalGroup(
            panelResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelResLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbRestaurantes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("¿QUÉ DESEA HACER?");

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel4.setText("Dar de baja a un restaurante");

        buttonGroup1.add(jDarDeBaja);
        jDarDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDarDeBajaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jModRes);
        jModRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModResActionPerformed(evt);
            }
        });

        buttonGroup1.add(jDarDeAlta);
        jDarDeAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDarDeAltaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jInfoCliente);
        jInfoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInfoClienteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel5.setText("Consultar información de un cliente");

        buttonGroup1.add(jVerInfoRes);
        jVerInfoRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVerInfoResActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel6.setText("Consultar información de un restaurante");

        buttonGroup1.add(botonVentas);
        botonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentasActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 0, 18)); // NOI18N
        jLabel7.setText("Consultar ventas");

        panelPedidos.setBackground(new java.awt.Color(255, 255, 255));

        cbPedidos.setModel(new javax.swing.DefaultComboBoxModel<>(Pedido.obtenerNombres(Sistema.getPedidos())));
        cbPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPedidosActionPerformed(evt);
            }
        });

        buttonFiltrarFecha.setText("Filtrar a partir de esta fecha");
        buttonFiltrarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFiltrarFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPedidosLayout = new javax.swing.GroupLayout(panelPedidos);
        panelPedidos.setLayout(panelPedidosLayout);
        panelPedidosLayout.setHorizontalGroup(
            panelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPedidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fechaElegida, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPedidosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonFiltrarFecha)
                .addGap(29, 29, 29))
        );
        panelPedidosLayout.setVerticalGroup(
            panelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPedidosLayout.createSequentialGroup()
                .addGroup(panelPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaElegida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(buttonFiltrarFecha)
                .addContainerGap())
        );

        panelClis.setBackground(new java.awt.Color(255, 255, 255));

        cbClientes.setModel(new javax.swing.DefaultComboBoxModel<>(Sistema.correosClientes(Sistema.clientesArrayList())));
        cbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClisLayout = new javax.swing.GroupLayout(panelClis);
        panelClis.setLayout(panelClisLayout);
        panelClisLayout.setHorizontalGroup(
            panelClisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        panelClisLayout.setVerticalGroup(
            panelClisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonVentas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDarDeAlta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDarDeBaja, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jModRes, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(394, 394, 394)
                        .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(panelRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(panelClis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(panelPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jInfoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jVerInfoRes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDarDeAlta)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jDarDeBaja))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jModRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jVerInfoRes))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInfoCliente)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonVentas)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelClis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        getParent().setVisible(true);
        dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * ejecuta una acción sobre los restaurantes dependiendo de que opcion haya sido previamente elegida por el administrador
     * @param evt 
     */
    private void cbRestaurantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRestaurantesActionPerformed
        Restaurante res;
        String eleccion = (String)cbRestaurantes.getSelectedItem();
        for (Restaurante rest: Sistema.restaurantesArrayList()){
            if (rest.getNombre().equals(eleccion)) {
                res = rest;
                if (jModRes.isSelected()){
                new JModRestaurante(res, this, true).setVisible(true);
                panelRes.setVisible(false);
                break;
                }else if (jDarDeBaja.isSelected()){
                    if (!Sistema.borrarRestaurante(res)) JOptionPane.showMessageDialog(this, "Ha ocurrido un error", "Error", JOptionPane.ERROR_MESSAGE);
                    else {
                        DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) cbRestaurantes.getModel();
                        model.removeElement(eleccion);
                        JOptionPane.showMessageDialog(this, "Se ha dado de baja al restaurante", "dar de baja", JOptionPane.INFORMATION_MESSAGE);
                    }
                break;
                }
                else if (jVerInfoRes.isSelected()){
                new JInfoRes(this, true, res).setVisible(true);
                panelRes.setVisible(false);
                break;
                }
            }
        }
        panelRes.setVisible(false);
    }//GEN-LAST:event_cbRestaurantesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Sistema.guardarDatosRestaurantes();
        Sistema.guardarDatosClientes();
        Sistema.guardarDatosPedidos();
    }//GEN-LAST:event_formWindowClosing

    private void jDarDeBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDarDeBajaActionPerformed
        if (jDarDeBaja.isSelected()){JOptionPane.showMessageDialog(this,"Seleccione el restaurante que quiere dar de baja");
        panelRes.setVisible(true);
        panelClis.setVisible(false);
        panelPedidos.setVisible(false);
        }
        
    }//GEN-LAST:event_jDarDeBajaActionPerformed

    private void jDarDeAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDarDeAltaActionPerformed
        if (jDarDeAlta.isSelected()){new JAltaRestaurante(this,true).setVisible(true);}
        else panelRes.setVisible(false);
    }//GEN-LAST:event_jDarDeAltaActionPerformed

    private void jModResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModResActionPerformed
        if (jModRes.isSelected()){
        panelRes.setVisible(true);
        panelClis.setVisible(false);
        panelPedidos.setVisible(false);
        }
        
    }//GEN-LAST:event_jModResActionPerformed

    private void jVerInfoResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVerInfoResActionPerformed
        if (jVerInfoRes.isSelected()){
            panelRes.setVisible(true);
            panelClis.setVisible(false);
            panelPedidos.setVisible(false);
                    }
        
    }//GEN-LAST:event_jVerInfoResActionPerformed

    private void jInfoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInfoClienteActionPerformed
        if (jInfoCliente.isSelected()){
            panelClis.setVisible(true);
            panelRes.setVisible(false);
            panelPedidos.setVisible(false);
        }
        
    }//GEN-LAST:event_jInfoClienteActionPerformed

    private void cbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbClientesActionPerformed
        Cliente cli;
        String eleccion = (String)cbClientes.getSelectedItem();
 
        for (Cliente clie: Sistema.clientesArrayList()){
            if (clie.getCorreoElectronico().equals(eleccion)) {
                cli = clie;
            if (jInfoCliente.isSelected()){
                new JInfoCli(this, true, cli).setVisible(true);
                panelClis.setVisible(false);
                }
            }
        }
    }//GEN-LAST:event_cbClientesActionPerformed
/**
 * muestra en el comboBox de pedidos solo los pedidos 
 * posteriores o simultaneos a la fecha introducida
 * 
 * @param evt 
 */
    private void buttonFiltrarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFiltrarFechaActionPerformed
        String fechaTexto = fechaElegida.getText().replaceAll("_", " ");
        LocalDateTime fecha = LocalDateTime.parse(fechaTexto, DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss"));
        boolean existe = false;
        for (Pedido pedido: Sistema.getPedidos()){
         if (pedido.getFecha().isAfter(fecha) || pedido.getFecha().isEqual(fecha)){
           int indice = Sistema.getPedidos().indexOf(pedido);
           ArrayList<Pedido> pedidosFiltrados =new ArrayList<>( Sistema.getPedidos().subList(indice, Sistema.getPedidos().size()));
           DefaultComboBoxModel model = new DefaultComboBoxModel(Pedido.obtenerNombres(pedidosFiltrados));
           cbPedidos.setModel(model);
           existe=true;
           break;
         }
             
        }if (!existe)JOptionPane.showMessageDialog(this, "No hay pedidos a partir de la fecha introducida", "Error en el filtrado", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_buttonFiltrarFechaActionPerformed

    private void botonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentasActionPerformed
        if (botonVentas.isSelected()){
            panelPedidos.setVisible(true);
            panelRes.setVisible(false);
            panelClis.setVisible(false);
        }
        
              
    }//GEN-LAST:event_botonVentasActionPerformed

    private void cbPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPedidosActionPerformed
        String clave = (String) cbPedidos.getSelectedItem();
        Pedido.abrirPedido(clave);
    }//GEN-LAST:event_cbPedidosActionPerformed

    public JComboBox<String> getCbRestaurantes() {
        return cbRestaurantes;
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonVentas;
    private javax.swing.JButton buttonFiltrarFecha;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbClientes;
    private javax.swing.JComboBox<String> cbPedidos;
    private javax.swing.JComboBox<String> cbRestaurantes;
    private javax.swing.JFormattedTextField fechaElegida;
    private javax.swing.JRadioButton jDarDeAlta;
    private javax.swing.JRadioButton jDarDeBaja;
    private javax.swing.JRadioButton jInfoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jModRes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jVerInfoRes;
    private Interfaz.Logo logo1;
    private javax.swing.JPanel panelClis;
    private javax.swing.JPanel panelPedidos;
    private javax.swing.JPanel panelRes;
    // End of variables declaration//GEN-END:variables
}
