package Interfaz;

import Logica.Catering;
import Logica.Comida;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class JCrearCatering extends javax.swing.JDialog {

    private ArrayList<Comida> comidasCatering = new ArrayList<>();
    private ArrayList <Comida> comidasRes;
    

    public ArrayList<Comida> getComidas() {
        return comidasCatering;
    }

    
    public JCrearCatering(javax.swing.JDialog parent, boolean modal, ArrayList<Comida> comidasRes) {
        super(parent, modal);
        this.comidasRes = comidasRes;
        initComponents();
        Logica.Sistema.centrarContainer(this);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jcamareros = new javax.swing.JCheckBox();
        jcocineros = new javax.swing.JCheckBox();
        jdecoracion = new javax.swing.JCheckBox();
        jespacio = new javax.swing.JCheckBox();
        jButtonHecho = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DefaultListModel model = new DefaultListModel();
        ArrayList<String> nombres = new ArrayList<>();
        for (Comida comida: comidasRes){
            nombres.add(comida.getTitulo());
        }
        model.addAll(nombres);
        listaComidas = new javax.swing.JList<>(model);
        logo1 = new Interfaz.Logo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jcamareros.setText("camareros");

        jcocineros.setText("cocineros");

        jdecoracion.setText("decoracion");

        jespacio.setText("espacio");

        jButtonHecho.setBackground(new java.awt.Color(255, 210, 136));
        jButtonHecho.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jButtonHecho.setText("HECHO");
        jButtonHecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHechoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("Escoja las comidas y las características de su catering");

        listaComidas.setToolTipText("pulsa tecla \"ctrl\" para seleccionar más de una comida");
        jScrollPane3.setViewportView(listaComidas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButtonHecho, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdecoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jespacio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcocineros, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcamareros, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jcamareros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcocineros))))
                    .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jdecoracion)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonHecho, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jespacio))
                .addContainerGap(319, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * crea un catering si se han seleccionado comidas 
 * y lo asocia a la variable Catering del Dialog padre
 * @param evt 
 */
    private void jButtonHechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHechoActionPerformed
        
        boolean cocineros = jcocineros.isSelected() ;
        boolean espacio = jespacio.isSelected();
        boolean decoracion = jdecoracion.isSelected();
        boolean camareros = jcamareros.isSelected();
        
        if (!listaComidas.isSelectionEmpty()){
            int[] indices = listaComidas.getSelectedIndices();
            for (int indice: indices){
                comidasCatering.add(comidasRes.get(indice));
            }
        }
        else {JOptionPane.showMessageDialog(this, "Es necesario escoger alguna comida");}
        
        Catering catering = new Catering(camareros,cocineros,decoracion,espacio,comidasCatering);
        JOptionPane.showMessageDialog(this, "Catering creado");
        if (getParent() instanceof JModRestaurante parent)parent.getRes().setCatering(catering);
        if (getParent() instanceof JAltaRestaurante parent)parent.setCatering(catering);
    }//GEN-LAST:event_jButtonHechoActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHecho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JCheckBox jcamareros;
    private javax.swing.JCheckBox jcocineros;
    private javax.swing.JCheckBox jdecoracion;
    private javax.swing.JCheckBox jespacio;
    private javax.swing.JList<String> listaComidas;
    private Interfaz.Logo logo1;
    // End of variables declaration//GEN-END:variables
}
