package Interfaz;
import Logica.Comida;
import  Logica.Pedido;
import Logica.Sistema;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;

public class JPedido extends javax.swing.JDialog {
    Pedido pedido;
    String clave;
    public JPedido(java.awt.Dialog parent, boolean modal, Pedido pedido) {
        super(parent, modal);
        
        this.pedido= pedido;
        initComponents();
        Sistema.centrarContainer(this);
       if (this.getParent() instanceof JRestaurante ){
       labelTEnvio.setText(String.valueOf(pedido.getRestauranteElegido().getTiempoEnvio()));
       Logica.Direccion domicilio= pedido.getCliente().getDireccion();
       String domicilioStr = domicilio.getCiudad()+", "+ domicilio.getCalle()+ ", nº: "+ domicilio.getNumero();
       labelDomicilio.setText(domicilioStr);
       LocalDateTime llegada = LocalDateTime.now().plusMinutes(pedido.getRestauranteElegido().getTiempoEnvio());
       
       labelLLegada.setText("El pedido llegaría sobre las: "+llegada.toLocalTime().toString().substring(0,5));
       jLabel5.setVisible(false);
       }else if (this.getParent() instanceof JPedirCatering){
           jLabel3.setVisible(false);
           jLabel4.setVisible(false);
           String text ="";
           if (pedido.getCatering().isCamareros())text+="camareros, ";
           if (pedido.getCatering().isCocineros()) text+="cocineros, ";
           if (pedido.getCatering().isDecoracion())text+= "decoracion, ";
           if (pedido.getCatering().isEspacio())text+="espacio";
           labelServicios.setText(text);
       }
       labelPrecio.setText(String.valueOf(pedido.getPrecio()));
        jPanel2.setVisible(false);
        setVisible(true);
        
        bImprimirFactura.setVisible(false);
    }
    String[][] obtenerResumen(ArrayList<Comida> comidas){
        HashMap<Comida, Integer> aux = new HashMap <>();
        for (Comida comida: comidas){
            if (!aux.containsKey(comida)){
                aux.put(comida, (int) comidas.stream().filter(t->t.equals(comida)).count());
            }
        }
        String[][] resumen = new String[aux.size()][2];
        int i =0;
        for (Comida com: aux.keySet()){
            resumen[i][0]= com.getTitulo();
            resumen[i][1]=  String.valueOf(aux.get(com));
            i++;
        }
        return resumen;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCom = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelDomicilio = new javax.swing.JLabel();
        labelTEnvio = new javax.swing.JLabel();
        botonPagar = new javax.swing.JButton();
        labelLLegada = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        sliderCalif = new javax.swing.JSlider();
        botonCalif = new javax.swing.JButton();
        bImprimirFactura = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labelServicios = new javax.swing.JLabel();
        logo1 = new Interfaz.Logo();
        labelGEnvio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(247, 192, 108));
        jLabel1.setText("Resumen del Pedido");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 214, 95)));

        if(this.getParent() instanceof JRestaurante parent){
            tablaCom.setModel(new javax.swing.table.DefaultTableModel(
                obtenerResumen(pedido.getCarritoCompra()),
                new String [] {
                    "Comida", "Cantidad"
                }
            ));
        }else{//viene de JPedirCatering
            tablaCom.setModel(new javax.swing.table.DefaultTableModel(
                obtenerResumen(pedido.getCatering().getComidasElegidas()),
                new String [] {
                    "Comida", "Cantidad"
                }
            ));
        }
        jScrollPane1.setViewportView(tablaCom);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel2.setText("Precio: ");

        labelPrecio.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        labelPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 213, 161)));

        jLabel3.setText("tiempo de envío:");

        jLabel4.setText("Domicilio: ");

        labelTEnvio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        botonPagar.setBackground(new java.awt.Color(255, 210, 153));
        botonPagar.setText("PAGAR");
        botonPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPagarActionPerformed(evt);
            }
        });

        labelLLegada.setBackground(new java.awt.Color(250, 237, 178));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        sliderCalif.setMaximum(500);
        sliderCalif.setToolTipText("");
        sliderCalif.setValue(0);

        botonCalif.setText("guardar calificación");
        botonCalif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalifActionPerformed(evt);
            }
        });

        bImprimirFactura.setBackground(new java.awt.Color(255, 153, 0));
        bImprimirFactura.setText("IMPRIMIR FACTURA");
        bImprimirFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bImprimirFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(sliderCalif, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(89, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonCalif)
                        .addGap(18, 18, 18)
                        .addComponent(bImprimirFactura)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(sliderCalif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCalif)
                    .addComponent(bImprimirFactura))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel5.setText("Servicios:");

        labelServicios.setBackground(new java.awt.Color(204, 255, 255));

        if (pedido.isPideCatering())labelGEnvio.setVisible(false);
        labelGEnvio.setText(String.valueOf(pedido.getRestauranteElegido().getGastosEnvio())+'€');

        jLabel6.setText("Gastos de envío:");
        if (pedido.isPideCatering())jLabel6.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(labelTEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(351, 351, 351))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonPagar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelLLegada, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(340, 343, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelGEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(264, 264, 264))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(labelPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(labelTEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(labelGEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(labelDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(labelServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLLegada, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPagar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPagarActionPerformed
        
        if (JOptionPane.showConfirmDialog(this, "Va realizar un pedido de "+labelPrecio.getText()+"€", "Confirmar Pago", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
             jPanel2.setVisible(true);
             pedido.finalizarPedido();
            Sistema.guardarFactura(pedido);
             bImprimirFactura.setVisible(true);
             Sistema.guardarDatosPedidos();
        }
       
    }//GEN-LAST:event_botonPagarActionPerformed

    private void botonCalifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalifActionPerformed
        double nota = sliderCalif.getValue()/100;
        sliderCalif.setEnabled(false);
        pedido.getRestauranteElegido().calificar(nota);
        JOptionPane.showMessageDialog(this, "Calificación guardada", "CALIFICAR", JOptionPane.PLAIN_MESSAGE);
        botonCalif.setVisible(false);
    }//GEN-LAST:event_botonCalifActionPerformed

    private void bImprimirFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bImprimirFacturaActionPerformed
       Pedido.abrirPedido(pedido.getClave());
    }//GEN-LAST:event_bImprimirFacturaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Sistema.guardarDatosPedidos();
        Sistema.guardarDatosRestaurantes();
    }//GEN-LAST:event_formWindowClosing
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bImprimirFactura;
    private javax.swing.JButton botonCalif;
    private javax.swing.JButton botonPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDomicilio;
    private javax.swing.JLabel labelGEnvio;
    private javax.swing.JLabel labelLLegada;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelServicios;
    private javax.swing.JLabel labelTEnvio;
    private Interfaz.Logo logo1;
    private javax.swing.JSlider sliderCalif;
    private javax.swing.JTable tablaCom;
    // End of variables declaration//GEN-END:variables
}
