package Interfaz;

import Logica.Catering;
import Logica.Comida;
import Logica.Pedido;
import Logica.Restaurante;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeListener;

public class JPedirCatering extends javax.swing.JDialog {

    Catering cateringPedido; //catering creado a partir del inicial por el cliente
    Restaurante res;
    Catering catering ;//catering inicial del restaurante escogido
    private ArrayList<Comida> comidasSeleccionadas = new ArrayList<>();

    public JPedirCatering(java.awt.Dialog parent, boolean modal,Restaurante res) {
        super(parent, modal);
        this.res=res;
        this.catering=res.getCatering();
        initComponents();
        Logica.Sistema.centrarContainer(this);
        if (catering.isCamareros()){
            jCamareros.setEnabled(true);
            jCamareros.setSelected(true);
        }
        if (catering.isCocineros()){
            jCocineros.setEnabled(true);
            jCocineros.setSelected(true);
        }
        if (catering.isDecoracion()){
            jDecoracion.setEnabled(true);
            jDecoracion.setSelected(true);
        }
        if (catering.isEspacio()){
            jEspacio.setEnabled(true);
            jEspacio.setSelected(true);
        }
        
        

        
       
        for (Comida com: res.getCatering().getComidasElegidas()){
            PanelComida panelcom = new PanelComida(com);
            panelcom.setSize(495, 145);
            jPanel1.add(panelcom);
            panelcom.getSpCantidad().addChangeListener(new ChangeListener() {
                @Override
                /**
                 * añade o quita 10 veces la comida del ArrayList de las comidas del catering
                 * Lo hace cada vez que se presiona el spCantidad
                 */
                public void stateChanged(javax.swing.event.ChangeEvent evt) {
                    int veces = (int)comidasSeleccionadas.stream().filter(t->t.equals(com)).count();
                    if ((int)panelcom.getSpCantidad().getValue()<veces) for (int i =0; i<10;i++) comidasSeleccionadas.remove(com);
                    else for(int i =0; i<10; i++) comidasSeleccionadas.add(com);
                    
                }
            });
        }
        setVisible(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jCamareros = new javax.swing.JCheckBox();
        jCocineros = new javax.swing.JCheckBox();
        jDecoracion = new javax.swing.JCheckBox();
        jEspacio = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        botonPedir = new javax.swing.JButton();
        logo1 = new Interfaz.Logo();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 235, 169));

        jCamareros.setText("camareros");
        jCamareros.setEnabled(false);

        jCocineros.setText("cocineros");
        jCocineros.setEnabled(false);

        jDecoracion.setText("decoracion");
        jDecoracion.setEnabled(false);

        jEspacio.setText("espacio");
        jEspacio.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel4.setText("Catering:");

        botonPedir.setBackground(new java.awt.Color(255, 234, 185));
        botonPedir.setText("Pedir catering");
        botonPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPedirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonPedir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel4))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jCamareros, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCocineros, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDecoracion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCamareros)
                            .addComponent(jCocineros)
                            .addComponent(jDecoracion)
                            .addComponent(jEspacio)))
                    .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonPedir)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 112, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 347, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * crea el catering y el pedido si hay comidas seleccionadas
     * Abre una ventana del pedido
     * @param evt 
     */
    private void botonPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPedirActionPerformed
        
        if(!comidasSeleccionadas.isEmpty()){
            cateringPedido = new Catering (jCamareros.isSelected(), jCocineros.isSelected(), jDecoracion.isSelected(), jEspacio.isSelected(), comidasSeleccionadas);
        
        DialogPrincipal parent = (DialogPrincipal) this.getParent().getParent();
        Pedido ped = new Pedido(parent.getCliente(), res, cateringPedido);
        new JPedido(this,true,ped);
        }else JOptionPane.showMessageDialog(this, "Se debe seleccionar al menos una comida", "No se pudo realizar el pedido", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_botonPedirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPedir;
    private javax.swing.JCheckBox jCamareros;
    private javax.swing.JCheckBox jCocineros;
    private javax.swing.JCheckBox jDecoracion;
    private javax.swing.JCheckBox jEspacio;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private Interfaz.Logo logo1;
    // End of variables declaration//GEN-END:variables


}
