package Interfaz;

import Logica.*;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeListener;

public class JRestaurante extends javax.swing.JDialog {
    Restaurante res;
    private ArrayList<Comida> comidasSeleccionadas = new ArrayList<>();
    /**
     * Crea la ventana JRestaurante y añade los paneles de la comida
     * @param parent
     * @param modal
     * @param res
     */
    public JRestaurante(javax.swing.JDialog parent, boolean modal, Restaurante res) {
        super(parent, modal);
        this.res= res;
        initComponents();
        Sistema.centrarContainer(this);
        for (Comida com: res.getComidas()){
            PanelComida panelcom = new PanelComida(com);
            panelcom.setSize(495, 145);
            jPanel1.add(panelcom);
            panelcom.getSpCantidad().setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

            panelcom.getSpCantidad().addChangeListener(new ChangeListener() {
                @Override
                /**
                 * añade o quita la comida del ArrayList de las comidas del catering
                 * Lo hace cada vez que se presiona el spCantidad
                 */
                public void stateChanged(javax.swing.event.ChangeEvent evt) {
                    int veces = (int)comidasSeleccionadas.stream().filter(t->t.equals(com)).count();
                    if ((int)panelcom.getSpCantidad().getValue()<veces) comidasSeleccionadas.remove(com);
                    else  comidasSeleccionadas.add(com);
                    
                }
            });
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        termPed = new javax.swing.JButton();
        logo1 = new Interfaz.Logo();
        botonPedCatering = new javax.swing.JButton();
        labelNombreRes = new javax.swing.JLabel(res.getNombre());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.setLayout(new BoxLayout(jPanel1,BoxLayout.Y_AXIS));

        jScrollPane1.setViewportView(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 235, 169));

        termPed.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        termPed.setText("Terminar Pedido");
        termPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termPedActionPerformed(evt);
            }
        });

        botonPedCatering.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        botonPedCatering.setText("Pedir Catering");
        DialogPrincipal parent = (DialogPrincipal) getParent();
        if (parent.getCliente() instanceof ClientePersonal ) botonPedCatering.setVisible(false);
        botonPedCatering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPedCateringActionPerformed(evt);
            }
        });

        labelNombreRes.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(termPed, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonPedCatering, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelNombreRes, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelNombreRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(termPed, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(botonPedCatering, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       Sistema.guardarDatosClientes();
        Sistema.guardarDatosRestaurantes();
        getParent().setVisible(true);
        
    }//GEN-LAST:event_formWindowClosing
    /**
     * comprueba que haya comidas seleccionadas y 
     * en tal caso abre una ventana Pedido asociada al pedido realizado
     * @param evt 
     */
    private void termPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termPedActionPerformed
    if (!comidasSeleccionadas.isEmpty()){
            DialogPrincipal principal = (DialogPrincipal) JRestaurante.this.getParent();
            Logica.Pedido pedido = new Logica.Pedido(principal.getCliente(),res,comidasSeleccionadas);
            
            new JPedido(JRestaurante.this , true, pedido);
            }
            else JOptionPane.showMessageDialog(JRestaurante.this, "No hay comidas elegidas", "ERROR AL HACER EL PEDIDO", JOptionPane.ERROR_MESSAGE);
            }//GEN-LAST:event_termPedActionPerformed

    private void botonPedCateringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPedCateringActionPerformed
        new JPedirCatering(JRestaurante.this,true,res);    }//GEN-LAST:event_botonPedCateringActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPedCatering;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNombreRes;
    private Interfaz.Logo logo1;
    private javax.swing.JButton termPed;
    // End of variables declaration//GEN-END:variables
}
